### ISSUE TITLE
Help: could not install Tabby properly

### ISSUE THREAD

**Issue by VKondakoff** [nanozuki/tabby.nvim#10]
Hi!

I'm trying to install Tabby using the instructions (macOS, iTerm2, Neovim nightly, Packer).
Here is what I see after running `:PackerInstall` and `:PackerCompile`:
<img width="791" alt="Снимок экрана 2021-10-06 в 13 11 07" src="https://user-images.githubusercontent.com/230824/136184190-7c68d273-219d-4cd8-8549-a65e246b26ad.png">

And here is what I see after restarting Neovim:
<img width="791" alt="Снимок экрана 2021-10-06 в 13 11 25" src="https://user-images.githubusercontent.com/230824/136184263-20558a65-71fd-41b6-832e-19643765c005.png">

What am I doing wrong? (Quite a newbie here.)
Thanks!

**Comment by VKondakoff** [comment]
Hi, nanozuki!

Thanks for helping me!

Second image: this just happens after restarting Neovim - for some reason Tabby is not shown after restart. No error messages are shown. Here is a short video:
https://www.dropbox.com/s/be9l11qxy9eq81k/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202021-10-06%20%D0%B2%2015.29.21.mov?dl=0

```lua
require('packer').startup(function()
  use 'wbthomason/packer.nvim' -- Packer can manage itself
  use {
    "nanozuki/tabby.nvim",
    requires = "kyazdani42/nvim-web-devicons",
    config = function() require("tabby").setup() end,
  }
end)
```
Is this code enough to show Tabby or I should call it somewhere else?

**Comment by EdenEast** [comment]
Are you able to reproduce the issue with a `minimal_init.lua` file? Try running the minimal setup below and see if you are still having issues. Also note in the file I am making sure that a colorscheme is applied before tabby's `setup` function.

```lua
-- Open with `nvim --clean -u minimal_init.lua`
local install_path = "/tmp/nvim/site/pack/packer/start/packer.nvim"
local compile_path = install_path .. "/plugin/packer_compiled.lua"
vim.opt.packpath = "/tmp/nvim/site"

local function load_plugins()
  local packer = require("packer")
  local use = packer.use
  packer.reset()
  packer.init({ compile_path = compile_path, package_root = "/tmp/nvim/site/pack" })

  use("wbthomason/packer.nvim")
  use({
    "edeneast/nightfox.nvim", -- Adding some sort of colorscheme
    config = function()
      vim.cmd("colorscheme nightfox")
    end,
  })
  use({
    "nanozuki/tabby.nvim",
    requires = "kyazdani42/nvim-web-devicons",
    after = "nightfox.nvim",
    config = function()
      require("tabby").setup()
    end,
  })
  packer.sync()
end

_G.load_config = function() end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by EdenEast** [comment]
I know it works with statuslines like [feline.nvim](https://github.com/famiu/feline.nvim) and [lualine](https://github.com/shadmansaleh/lualine.nvim) (current maintained fork). Looking at lightline it looks like it does the tabline as well. They are conflicting.

**Comment by Hdoc1509** [comment]
Hi @VKondakoff , I know this is an old issue, but her I go,

You can disable the `tabline` feature of `lightline.vim` with the following code:
```lua
vim.g.lighline = {
  ...other_options,
  enable = { tabline = 0 },
}
```

**Comment by Hdoc1509** [comment]
Hi @VKondakoff , I know this is an old issue, but her I go,

You can disable the `tabline` feature of `lightline.vim` with the following code:
```lua
vim.g.lighline = {
  ...other_options,
  enable = { tabline = 0 },
}
```
