### ISSUE TITLE
Tabline Background Seems Corrupted

### ISSUE THREAD

**Issue by mebaran** [nanozuki/tabby.nvim#109]
I really like this plugin except I have weird white bars that make the tab bar look ugly.  I'm using the Seoul256 theme for these screenshots (both with and without nerdfonts).  How can I fix it?  Attached images show issue.

<img width="1150" alt="tabby nvim look problem 2" src="https://user-images.githubusercontent.com/66722/221453910-e5d1bc68-0a99-4243-a1ba-a472b6c8c899.png">
<img width="696" alt="tabby nvim tab look problem" src="https://user-images.githubusercontent.com/66722/221453918-280ad2c0-6cd5-4845-8e32-6f3442afa5b1.png">

Neovim Info:

:version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

**Comment by nanozuki** [comment]
Can you tell me the config of tabby?

**Comment by mebaran** [comment]
Here's my config for statuslines: 

```
local function lualine_setup ()
    require('lualine').setup({
        globalstatus = true
    })
end

local function tabby_setup ()
    require('tabby.tabline').use_preset('active_wins_at_tail')
end

return {
    {
        "nvim-lualine/lualine.nvim",
        config = lualine_setup
    },
    {
        "nanozuki/tabby.nvim",
        config = tabby_setup
    }
}
```

**Comment by nanozuki** [comment]
I found that highlights of the theme 'Seoul256' set are not completed for tabby's separator. So the separator color is wrong. You can apply a theme object to the preset. I found a valid value by follow the lualine's theme:

```lua
require('tabby.tabline').use_preset('active_wins_at_tail', {
  theme = {
    fill = 'Visual',
    tab = 'StatusLine',
    win = 'StatusLine',
    head = 'StatusLine',
    tail = 'StatusLine',
  },
})
```

The preview is:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/4208028/222059499-31f272e0-2f69-428f-a2bf-9e44d6cec669.png">

You can use `:highlight` command to choose what highlight you want to use. Or you can specify the color from Seoul256's color palette, for example: 

```lua
require('tabby.tabline').use_preset('active_wins_at_tail', {
  theme = {
    ...
    tab = { fg = '#dfe0e0',  guibg=#545454 },
    ...
  },
})
```

**Comment by mebaran** [comment]
This worked perfectly.  I noticed this issue in several other themes; maybe
it would make sense to make it a theme fix up option for lualine users?
Now the plugin works great!

Best,
Mark

**Comment by nanozuki** [comment]
I'm glad it helps.

> maybe it would make sense to make it a theme fix up option for lualine users?

Oh! I think this is a justifiable suggestion since the `lualine` looks like the most popular line plugin.

**Comment by nanozuki** [comment]
@mebaran After version v2.2.0, the user can use Lualine's theme in presets.
