### ISSUE TITLE
Changing colorscheme without restarting causes inconsistent highlighting

### ISSUE THREAD

**Issue by loqusion** [nanozuki/tabby.nvim#112]
To be clear, the colors appear just fine if I just change the colorscheme in my nvim config. Like so:

### gruvbox-material

<img width="789" alt="Screenshot 2023-04-12 at 10 58 24 PM" src="https://user-images.githubusercontent.com/38332081/231649010-fb9e579b-4f5d-4814-b495-b09f10c4af3b.png">

### ayu

<img width="789" alt="Screenshot 2023-04-12 at 10 58 48 PM" src="https://user-images.githubusercontent.com/38332081/231649108-719efe73-c063-4232-b1c1-9e4dd9139afb.png">

However, if I change the colorscheme while nvim is running, the tab highlights become inconsistent (similar to #81):

https://user-images.githubusercontent.com/38332081/231649478-386ac825-aacd-4f76-a9d6-e2405939dbb3.mov

---

#### NeoVim version

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

#### Tabby config

```lua
require('tabby').setup()
```

#### Colorschemes
[gruvbox-material](https://github.com/sainnhe/gruvbox-material)
[ayu](https://github.com/Shatur/neovim-ayu)

**Comment by nanozuki** [comment]
Can you tell me the repository address of the colorscheme you use and the configuration of the tabby?

**Comment by loqusion** [comment]
@nanozuki Sure, I've edited the issue to add the colorscheme links and tabby config.

**Comment by nanozuki** [comment]
Oh... I noticed that you are using the v1.x version config function. And the v1.x version have some legacy bugs. I remain it only for backward compatibility.

You can use the v2 config to fix it (I tested it): 

```lua
require('tabby.tabline').use_preset('active_wins_at_tail')
```

**Comment by nanozuki** [comment]
If there is some other issue, you are welcome to discuss it here
