### ISSUE TITLE
About the highlight extraction routine

### ISSUE THREAD

**Issue by TinusgragLin** [nanozuki/tabby.nvim#118]
I recently switched my color scheme to [gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim) and noticed that the separators turned white: 
![2023-08-05_20-13-49](https://github.com/nanozuki/tabby.nvim/assets/57218218/22c760bd-554f-41e6-86c2-13a840ca1896)

I compared highlight settings of gruvbox.nvim with that of other color schemes and suspected that `Tabline` being linked to `TablineFill` might be the problem, then I further checked tabby's source code and noticed that [`highlight.extract`](https://github.com/nanozuki/tabby.nvim/blob/8bbd8b15c15b69057260170355b8e7adcca1c11a/lua/tabby/module/highlight.lua#L58) does not handle highlight linking. 

While this can be fixed easily, I wonder why we are not using `nvim_get_hl` to extract information about a  certain highlight group as it is simpler and more reliable.

**Comment by nanozuki** [comment]
Oh..., I write the plugin when nvim 0.5.0. In that version, there is no nvim_get_hl. Since the neovim 0.9 is already released some days, I think this project should use more lua APIs.

Thanks for your reminder, I try to fix this.

**Comment by nanozuki** [comment]
`nvim_get_hl` and `nvim_set_hl` will import breaking updates in the current version. I will put them in next version.
So I fixed this issue in old way (match string). I will open another issue to make tabby.nvim to use pure lua api.
