### ISSUE TITLE
How to show all buffers in tab?

### ISSUE THREAD

**Issue by DuyDuong437** [nanozuki/tabby.nvim#123]
Currently tabby only shows maximum of 2 buffers in a tab.

How to show all buffers available in tabs?

**Comment by nanozuki** [comment]
In preset config, tabby shows all **windows** in a tab. It doesn't have a limit to show a maximum of 2 windows.
Buffers are not "belong to" tab, so we can't find all the buffers in the tab. Let me try to explain it:

Maybe we open 2 tabs and 5 windows:
```
Tab 1: Window A: view.py Window B: service.py
Tab 2: Window A: view.py Window B: sql.py Window C: README.md
```

And the buffers are:

```
buffer 1: view.py
buffer 2: service.py
buffer 3: sql.py
buffer 4: README.md
buffer 5: app.py (not shown)
```

**Comment by nanozuki** [comment]
I closed this issued. Further more discussion is welcome
