### ISSUE TITLE
Change the lazy install code

### ISSUE THREAD

**Issue by Xczer** [nanozuki/tabby.nvim#128]
i dont know where to post this but i found that the lazy code u guys have written have one thing wrong in it...when i try to install it it gives me error about the spelling of fucntion which funcion like;;delete this issue bcoz this plugin is awesome just wanted to tell a minor mistake from my end

**Comment by nanozuki** [comment]
Oh, my mistake! @wvell help me to fix this, you can check the lastest README.
https://github.com/nanozuki/tabby.nvim/pull/127
