### ISSUE TITLE
Keep working directory per tab

### ISSUE THREAD

**Issue by PangPangPangPangPang** [nanozuki/tabby.nvim#13]
Thanks for your plugin first.
But why 'cd' command changed the cwd of all tabs

**Comment by nanozuki** [comment]
If you want only to change cwd for a tab page, you should use `:tcd`. The `:cd` will change the cwd for the whole nvim.
Furthermore, `:lcd` will change the cwd only for the current window.

**Comment by PangPangPangPangPang** [comment]
Thanks!
