### ISSUE TITLE
Plugin sets showtabline option to 2 when enabled

### ISSUE THREAD

**Issue by Demianeen** [nanozuki/tabby.nvim#134]
Hi! Just came across your nice plugin and wanted to use it. I happen to stumble on unexpected (at least for me) behaviour described above. Take a look:

https://github.com/nanozuki/tabby.nvim/assets/51330172/fe05bd8c-8573-4e87-a049-0059613e6816

Is it expected?

I use last nightly and last MacOS Sonoma

**Comment by Demianeen** [comment]
Workaround for now:
```lua
return {
	'nanozuki/tabby.nvim',
	event = 'VimEnter',
	dependencies = 'nvim-tree/nvim-web-devicons',
	opts = {},
	config = function(_, opts)
		require('tabby').setup(opts)
		vim.o.showtabline = 1
	end
}
```

**Comment by nanozuki** [comment]
Oh，for back compatibility, the default setup (and lazy's opt) still fits v1. You can check
- [User Presets](https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#Use-Presets)
- [Set customize Config](https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#customize)
