### ISSUE TITLE
Colorschemes not displaying correctly.

### ISSUE THREAD

**Issue by w3irdsloth** [nanozuki/tabby.nvim#136]
Hello, this looks like a really nice plugin but I'm having trouble getting it to display properly. I've reviewed previous issues, including #118 and #112 , which both seem similar to my issue but the tab highlights are always the wrong color, even when setting the theme in the config:

![2024-05-02-000452_hyprshot](https://github.com/nanozuki/tabby.nvim/assets/18625349/9227f5b2-1205-40d5-a565-ae2a79944e1a)

I've currently just got 
`require('tabby.tabline').use_preset('active_wins_at_tail')`
in my init.lua file and have used various themes but nothing seems to change it. I also used the custom config and tried to change the individual settings, but the highlight behind the nerdfont 'slashes' never seems to match the tab correctly. Is there a setting I'm missing? Thanks for the help and the hard work!

**Comment by EpsilonKu** [comment]
It can be due to theme issue. Did u other plugins like barbar.nvim and scope.nvim?

**Comment by w3irdsloth** [comment]
Yes I've used barbar but not scope. I created an empty init.lua file and tried different configs there. It looked pretty good with the minimal config without the nerdfonts so I'll just go with that or one of the other plugins for now.

**Comment by EpsilonKu** [comment]
Lol, I mean to try to test it. What's ur colorscheme? Lemme test it?

**Comment by w3irdsloth** [comment]
Hi, yes I've used barbar, bufferline, and lualine's tabline. The themes all display correctly. I'm using the gruvbox theme  currently but it's not working with the default, gruvbox-material, or everforest.

**Comment by nanozuki** [comment]
If you can accept the lualine's theme, you can use it in tabby; check https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#use-presets.

Since there are several Gruvbox themes, can you tell me the exact repo address for your theme? I'd like to receive more feedback.

**Comment by w3irdsloth** [comment]
I tried the code, but it didn't work right either. I'm using the theme from: https://github.com/morhetz/gruvbox/.

**Comment by w3irdsloth** [comment]
OK. I think I get the issue. I just need to try more themes. It was confusing me because even after changing to various default themes it wasn't picking up correctly but it needed to have a base theme set that works with the plugin. 
This gruvbox theme works great: https://github.com/luisiacc/gruvbox-baby/.  
This one doesn't apply the theme correctly but then looks ok when switched to a default: https://github.com/ellisonleao/gruvbox.nvim/
These two didn't work for me well at all, like the one I posted above: https://github.com/gruvbox-community/gruvbox/
https://github.com/lifepillar/vim-gruvbox8/

I think this clarifies my problem. I'll go ahead and close the issue out. Thanks for pointing me in the right direction!
