### ISSUE TITLE
Nvim api `vim.tbl_islist` is deprecated on nightly version

### ISSUE THREAD

**Issue by chasing-freedom** [nanozuki/tabby.nvim#139]
Warning Message in Neovim

> Warn  11:45:31 PM notify.warn vim.tbl_islist is deprecated, use vim.islist instead. :help deprecated
> Feature will be removed in Nvim 0.12
> Warn  11:45:31 PM notify.warn stack traceback:
> 	vim/shared.lua: in function 'tbl_islist'
> 	...l/share/nvim/lazy/tabby.nvim/lua/tabby/module/render.lua:50: in function 'render'
> 	[string "luaeval()"]:1: in main chunk

The official website [ docs link ](https://neovim.io/doc/user/deprecated.html#vim.tbl_islist()) about this issue.

**Comment by nanozuki** [comment]
I upgrade to 0.10 for the first time. I already thinking of this. I worried that if I removed these deprecated functions, users who have not upgraded can't use tabby.nvim.

For the workaround, you can add this to your config to disable deprecated notifications.
```lua
vim.deprecate = function() end
```

I will find way to avoid notifications and not break capabilities.
