### ISSUE TITLE
Feat: magic jump (jump to tab via letter)

### ISSUE THREAD

**Issue by ilan-schemoul** [nanozuki/tabby.nvim#143]
Hey,
Great plugin.
The only problem I have is that I tend to have multiple (5/6 tabs) and selecting via UI.select is not fast compared to the great approach of barbar : you type the keybind to do the "magic jump" then the first letter (if available) of the tab name
https://github.com/romgrk/barbar.nvim/blob/master/static/jump.gif?raw=true
As I don't have the time to port this feature here (nor do I wanna use barbar) I use a package for telescope to select tabs but it's not as conveniant or cool
If anybody has any interest for developing that it would be an awesome feature

**Comment by nanozuki** [comment]
Do you have interest or time to add your telescope picker to "tabby.nvim"? Adding a more method to do this makes it more friendly for users.

**Comment by ilan-schemoul** [comment]
I'm glad you like the idea :)

> Do you have interest or time to add your telescope picker to "tabby.nvim"? Adding a more method to do this makes it more friendly for users.

I didn't make the picker. This is what I'm using https://github.com/LukasPietzschmann/telescope-tabs

**Comment by nanozuki** [comment]
@ilan-schemoul How do you think about opening a popup window and setting some keybinding to pick a tab?

**Comment by ilan-schemoul** [comment]
Well I think what's nice about the magic jump is that it doesn't interrupt my flow of thoughts : I think I want to go to tabs xyz so I type <leader>tx (if <leader>t is to pick a tab). Popup tend to add mental overhead and breaks mental flow a little bit. I would even add that it's what I like about vim I can just do anything via keyboard without my mental flow being disturbed by any kind of UI.

So if we can manage to have something like barbar where when we start magic jump the first letter (or second if the first letter is already used) appears in red and we just type it it would be awesome.
If it's too complex I'd understand I can stick with the telescope plugin it's not huge deal.

**Comment by nanozuki** [comment]
I think I found a way to implement this. I expect to complete it this month.

**Comment by nanozuki** [comment]
I'm too busy these two days, sorry for being late. I think this feature has been implemented. Check it at [jump mode](https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#jump-mode-for-tabs).

Welcome any further feedback!

**Comment by ilan-schemoul** [comment]
No need to apologize open source is about doing voluntary contributions when we feel like it.

I tested it. It works good. Is there a way to customize the color ? Cause it doesn't stand out enough on my config (which is flat, no colors, no separations)
