### ISSUE TITLE
`win` is no longer a TabbyWin table

### ISSUE THREAD

**Issue by avegancafe** [nanozuki/tabby.nvim#165]
Not sure the best way to describe this, but I upgraded from a old-ish version and went to start vim and digging through the source code it seems like the tabs returned by `line.tabs` had a method on them called `wins` that returned a `TabbyWin` that had methods like `is_changed` and such, but it's just the window ids. Is this expected? In the documentation it says that `tab.wins()` returns `tabby-wins`, which I thought would be the `win` type

**Comment by nanozuki** [comment]
Thanks for your feedback; I fixed it in the master branch.
I wonder why my LuaLS does not warn me of the type mismatch!
