### ISSUE TITLE
Unnamed buffers always get the name of the current directory

### ISSUE THREAD

**Issue by mikaraunio** [nanozuki/tabby.nvim#169]
Following up to [#160](https://github.com/nanozuki/tabby.nvim/issues/160#issuecomment-2503015750):

> Replacing cur_win with vim.fn.winbufnr(cur_win) does give me the correct filename, but strangely, it gives the current path for unnamed buffers instead of [No Name]

Even with the stock config (or any of the presets), all my unnamed buffers now have the name of the current working directory in the tab bar, instead of `[No Name]`.

nvim version:
```
NVIM v0.11.0-dev-1306+gec94c2704f-Homebrew
Build type: Release
LuaJIT 2.1.1732813678
Run ":verbose version" for more info
```

Config to reproduce:
```lua
return {
  {
    'nanozuki/tabby.nvim',
    opts = {},
  },
}
```

**Comment by mikaraunio** [comment]
Ah, actually:

What I'm seeing is that all unnamed buffers get the name of the **active window's** current directory, instead of the cwd of their own window.

**Comment by nanozuki** [comment]
Fixed in leatest commint and version.
