### ISSUE TITLE
The newly created tab with no buffer have a current dir as a window name in tabline

### ISSUE THREAD

**Issue by VKondakoff** [nanozuki/tabby.nvim#17]
Hi!

The newly created tab with no buffer (:tabnew) have a current dir as a window name in tabline:
<img width="818" alt="Снимок экрана 2021-10-10 в 01 52 54" src="https://user-images.githubusercontent.com/230824/136675664-50b0dc0f-b75b-441d-a4af-8bc4bba935b3.png">

I'm pretty sure it should be 'No name' instead.
(macOS, iTerm2, Neovim nightly)

**Comment by nanozuki** [comment]
Oh, that is a miss. I will fix it

**Comment by nanozuki** [comment]
Fix in latest commit.
