### ISSUE TITLE
Default tab style looks broken

### ISSUE THREAD

**Issue by GabMus** [nanozuki/tabby.nvim#31]
The image shows the problem.

![image](https://user-images.githubusercontent.com/1358527/145430902-46cbfd73-7c8a-4094-b092-c45cc48f4a07.png)

I'm using the `nerd-fonts-jetbrains-mono` font from the Arch User Repository, this same problem occurs in VTE based terminals, as well as in alacritty and konsole.

Using `ttf-nerd-fonts-symbols` from the Arch repos shows a similar problem with the glyphs:

![image](https://user-images.githubusercontent.com/1358527/145434906-1f35ce91-e482-448b-ba25-cd48f727eff5.png)

Using other nerd font patched fonts like hack shows yet the same problem.

**Comment by GabMus** [comment]
- [Alacritty config](https://gitlab.com/gabmus/mydotfiles/-/tree/master/alacritty/dot-config/alacritty)

And here's the current font setting for tilix (current VTE terminal I'm using, confirmed to be broken even with other terminals):

![image](https://user-images.githubusercontent.com/1358527/146521546-f8be6669-7349-41a7-bf3a-345fe02f01d7.png)

No point in showing you different font selections in a screenshot, in both alacritty and tilix I tried:

- `JetBrains Mono` + `ttf-nerd-fonts-symbols`
- `JetBrains Mono NL` (no ligatures) + `ttf-nerd-fonts-symbols`
- [JetBrains Mono patched for nerdfonts](https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono/) and [this other variant as well](https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono-160/)

**Comment by chananababa** [comment]
I have the same issue with the following iterm config.

![스크린샷 2022-08-11 오후 11 02 16](https://user-images.githubusercontent.com/62169778/184151433-84bfda24-7535-4b91-bef1-9bd5a8a7f931.png)

**Comment by nanozuki** [comment]
For now,  I know the answers

@GabMus  You should use the matching need font, not a different font; for example, JetBrains Mono should use JetBrains Mono NerdFont, not ttf-nerd-fonts-symbols.

@chananababa In iTerm2，should use the `Hack Nerd Font Mono`
