### ISSUE TITLE
[Feature Request] Option to show tabline only if there are 'n' tabs open

### ISSUE THREAD

**Issue by luiz00martins** [nanozuki/tabby.nvim#32]
Currently, tabby will show the tabline even when there's only one tab open. It'd be nice if you had the option to show it only when there are multiple tabs open, the same way it works with the vanilla one.

I think this could be implemented as an option like `show_when_n_or_more_tabs`. With the default `1`, it'd always show the tabline. However when changed to `2`, it'd only show the tabline when you have 2 or more tabs open, and changing to `3` would only show when there are 3 or more open.

**Comment by nanozuki** [comment]
Oh..I think this is necessary, but I missed it. I will add this for the next version.

**Comment by nanozuki** [comment]
@luiz00martins Now you can use 

```lua
{
  opt = {
    show_at_least = 2,
  },
}
```

to reach your goal.
