### ISSUE TITLE
Filter certain window labels / titles from appering in the bar

### ISSUE THREAD

**Issue by ghillb** [nanozuki/tabby.nvim#34]
A filter config key for certain windows to hide from the bar would be an useful addition.

An example would be the 'index' window label, when opening fugitives git status with `:G` or terminal window labels the user does not deem as valuable. 

![2021-12-28-140450_1501x70_scrot](https://user-images.githubusercontent.com/35503959/147569866-cc1bbc2d-ca3e-4f9a-b2ad-2298ef073192.png)

On this pic, only the '[No name]' window label is useful to me.

**Comment by nanozuki** [comment]
I rewrite the config API in case to easily achieve this function. For example in [setup](https://github.com/nanozuki/tabby.nvim#setup), you can filter window like this:

```lua
line.wins_in_tab(line.api.get_current_tab()).foreach(function(win)
  if string.find(win.buf_name(), "^index") then
    return ''
  end
  ...
end),
```

**Comment by nanozuki** [comment]
If you want filter by buffer type, for example, don't display all 'nofile' buffer:

```lua
line.wins_in_tab(line.api.get_current_tab()).foreach(function(win)
  if win.buf().type == 'nofile' then
    return ''
  end
  ...
end),
```
If return an empty string, this window label won't be rendered.

You can check this for the detail of buf type: [neovim help: buftype](https://neovim.io/doc/user/options.html#'buftype')
