### ISSUE TITLE
Add a close tab icon

### ISSUE THREAD

**Issue by GabMus** [nanozuki/tabby.nvim#36]
It would be nice to be able to close tabs using a close button, similar to how bufferline does it.

Here's an example showing what it looks like in bufferline (not my config):

![image](https://user-images.githubusercontent.com/1358527/148525148-68793e17-22dc-43a5-8af3-899876ea6460.png)

**Comment by nanozuki** [comment]
Yes, it's in the plan. But I'm considering how to add new feature but not to break the configurable and customizable. I guess it won't take too long.

**Comment by nanozuki** [comment]
I rewrite the config API in case to easily add helper functions. For example in [setup](https://github.com/nanozuki/tabby.nvim#setup), you can add a close button by tab object:

```lua
line.tabs().foreach(function(tab)
  local hl = tab.is_current() and theme.current_tab or theme.tab
  return {
    line.sep('', hl, theme.fill),
    tab.is_current() and '' or '',
    tab.number(),
    tab.name(),
    tab.close_btn(''),
    line.sep('', hl, theme.fill),
    hl = hl,
    margin = ' ',
  }
end),
```

Detail: https://github.com/nanozuki/tabby.nvim#tab
