### ISSUE TITLE
Doesn't use colours from Dracula theme

### ISSUE THREAD

**Issue by lougreenwood** [nanozuki/tabby.nvim#38]
Somewhat surprisingly given how mature the Dracula theme is, it seems that `tabby` doesn't use colours from that theme, instead my tab bar has no selected tab highlights etc

Can confirm other themes work fine (e.g `onedarkhalf`).

![Screenshot](https://user-images.githubusercontent.com/12051736/149626891-c93e81fe-6e54-4b46-8c59-67d9cca9e6e2.png)

**Comment by nanozuki** [comment]
The vim/neovim ecosystem story is that the plugin announces the highlight groups used, and the theme author assigns values to these highlight groups. But tabby's key feature is highly configurable, so I have no way to announce several highlight groups and wait for the themes author to find this plugin.
I'm planning to develop the next version of tabby.nvim, I plan to make some preset styles from popular statusline/tabline plugins. It will provide a nice default config.

**Comment by nanozuki** [comment]
For now, you can use `require('tabby.util').extract_nvim_hl(<highlight>)` to extract a color from highlight.

**Comment by nanozuki** [comment]
The "decura" theme does not set background in highlight 'TabLineSel', preset in tabby will be a glitch. I think `onedarkhalf` is right. You can define your own color in tabby's tabline.
