### ISSUE TITLE
Scrollable?

### ISSUE THREAD

**Issue by rockyzhang24** [nanozuki/tabby.nvim#50]
Really love this pure tab plugin. I hate bufferline. 

Are you planning to support scrollable feature just in case the tabs are too many or too long that cannot fit into the screen? 

Thank you so much.

**Comment by nanozuki** [comment]
I have the plan, but I need some time to find a way to implement this.

**Comment by nanozuki** [comment]
I can't find docs for scrollable lines, can you give me some example plugins?

**Comment by EpsilonKu** [comment]
It seems they doesn't add it (https://github.com/akinsho/bufferline.nvim/issues/413). But barbar.nvim has auto-scroll.

**Comment by nanozuki** [comment]
It is difficult for the current design, so I achieved this before I found a way.

**Comment by avegancafe** [comment]
Was this ever implemented by any chance @nanozuki ? Struggling to find how to do this

**Comment by nanozuki** [comment]
@avegancafe I recently refactored the renderer in Tabby.nvim, I think it makes this feature possible to implement. First, I'm going to read some other plugin code to ensure a plan.

**Comment by nanozuki** [comment]
Because `tabby.nvim` is highly customizable, it's hard to find a normal way to truncate or scroll the tab line. I tried some plans, but all failed.

I will close this issue temporarily until someone finds a way.

**Comment by avegancafe** [comment]
Hmm maybe it could be configurable where there's like a "Windowed tabs" list exported and you can set plus or minus how many tabs you want to be able to display at once in the tab bar? I'll try to put up a PR if I come up with anything that feels like it could be generalized in my config

**Comment by nanozuki** [comment]
> Hmm maybe it could be configurable where there's like a "Windowed tabs" list exported and you can set plus or minus how many tabs you want to be able to display at once in the tab bar? I'll try to put up a PR if I come up with anything that feels like it could be generalized in my config.

Maybe this is a great way! You are welcome to share more information. If I come up with something, I will update you here, too.
