### ISSUE TITLE
missing argument guibg=

### ISSUE THREAD

**Issue by Maddin-619** [nanozuki/tabby.nvim#55]
Today after updating I got these error message:
<img width="967" alt="Snipaste_2022-05-11_08-16-28" src="https://user-images.githubusercontent.com/19187483/167788864-cb1c86c5-61e7-47d4-9dee-c78ff96213df.png">

The error also appears with the default style.

Figured out, that hl.bg passes the vim.validate function (not nil) but is an empty string. Maybe we should check that too:
```lua
  if hl.bg ~= nil and hl.bg ~= "" then
    table.insert(cmd, 'guibg=' .. hl.bg)
  end
```

**Comment by nanozuki** [comment]
Thank you! I fixed it.
