### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by mwoods79** [nanozuki/tabby.nvim#56]
When I run `:PackerSync` I get the following error.
`packer.nvim: Error running config for tabby.nvim: vim/shared.lua:0: after the second argument: expected table, got nil`

Here is my config.
```lua
  use { "nanozuki/tabby.nvim",
    requires = "kyazdani42/nvim-web-devicons",
    after = "nightfox.nvim",
    config = function()
      require("tabby").setup({})
    end
  }
```

**Comment by nanozuki** [comment]
I can't reproduce this bug on my device. Can you test with minimal config or share the whole configuration?

**Comment by mwoods79** [comment]
Seems like this was a packer issue. I removed all plugins except tabby and it worked. Then I re-installed each plugin, one at a time, to see which one caused the problem. Now I can't reproduce.

Thank you for your time. 

P.S. Thank you for this plugin. This plugin is exactly what I was looking for.
