### ISSUE TITLE
Hide windows showing non-file buffers

### ISSUE THREAD

**Issue by drinkitup777** [nanozuki/tabby.nvim#57]
There are certain tool windows, like file browsers and issues lister, that show up in the window list but don't represent actual documents. It might make more sense to hide them from the window list. It could be an option. What do you think?

---

![screenshot](https://user-images.githubusercontent.com/59168253/168205365-c7a6f1b6-5b9e-4810-ba59-32322d38a773.png)

**Comment by nanozuki** [comment]
Oh, I think this is a useful feature, I will try to add it.

**Comment by nanozuki** [comment]
Finally completed this feature; you can find that in this comment:
https://github.com/nanozuki/tabby.nvim/issues/34#issuecomment-1260343041
