### ISSUE TITLE
[Bug] Not finding tabby modules

### ISSUE THREAD

**Issue by luiz00martins** [nanozuki/tabby.nvim#64]
Upon running `require('tabby.filename')` and `require('tabby.util')`, I get the errors `module 'tabby.filename' not found` and `module 'tabby.util' not found`.

Is that a bug or were they removed?

**Comment by nanozuki** [comment]
It was never removed, can you check your plugins manager?

**Comment by luiz00martins** [comment]
Don't exacly know what you mean by that, but I'm using `packer` and my config is:
```lua
use {'nanozuki/tabby.nvim'}

plugin_configs['tabby'] = function()
	local filename = require('tabby.filename') -- Any of these
	local util = require('tabby.util')         -- two fail.

	-- The rest here doesn't execute, because the previous two fail.
	--variables
	--configs
	--stuff
end
```

```lua
-- In a place very far away, in a different file...
plugin_configs['tabby']()
```

**Comment by luiz00martins** [comment]
I ran a `:PackerSync`, and the problem disappeared... despite having no new commits from tabby

:|

**Comment by luiz00martins** [comment]
Just reinstalled my OS, and it came back after the fresh install. Suspecting it's something specific to my setup.

Gonna try to take some to debug it this week.

**Comment by nanozuki** [comment]
For the nvim lua environment, the module `tabby.filename` is in [/lua/tabby/filename.lua](https://github.com/nanozuki/tabby.nvim/blob/main/lua/tabby/filename.lua), and the module `tabby.util` is in [/lua/tabby/util.lua](https://github.com/nanozuki/tabby.nvim/blob/main/lua/tabby/util.lua).

So, this can't be an issue in `tabby.nvim`, please check the usage of the plugin manager. I'll close the issue, but we can also discuss this issue. 

Btw, won't forget to call `PackerCompile` when you change packer's config.

**Comment by luiz00martins** [comment]
Ultimately, the problem happened because I had an `after` clause:
```lua
use {
	'nanozuki/tabby.nvim',
	after = 'tokyonight.nvim',
}
```
That deferred tabby's execution so much, that when I *manually* called `require('tabby.filename')` later in my config, tabby wasn't loaded yet. (that's my best guess at least)

Removing the `after` clause and reinstalling tabby solved the problem.

**Comment by nanozuki** [comment]
As I mentioned, If you use `pakcer.nvim`, the best way to config the plugin is to put your plugin config in plugin declaration. Like this: 

```
use {
  'nanozuki/tabby.nvim',
  config = function()
    require('tabby').setup({})
  end
}
```

**Comment by luiz00martins** [comment]
I've had some issues with `config` in the past, so I opted out of it. Just decided to try it out again though, and it seems like it's working normally, so I'll use it in my configs. Thanks.
