### ISSUE TITLE
Highlighting problem: hi <group> cleared does not exists

### ISSUE THREAD

**Issue by SuperFola** [nanozuki/tabby.nvim#69]
This line introduced a bug when cmd length is 2, because it generates the command "hi group cleared" instead of "hi group guibg=cleared"

https://github.com/nanozuki/tabby.nvim/commit/e85cf1d23b310e5431090b937e3a315d81b14583#diff-22a223a33734b1de7e9d3ba974c3c6182519e16b846a399e9e30c19a8a9dffadR49

**Comment by nanozuki** [comment]
Oh, my fault. I'll fix it right now
