### ISSUE TITLE
Is there any way to toggle the plugin on and off?

### ISSUE THREAD

**Issue by Pocco81** [nanozuki/tabby.nvim#80]
If not then would it be possible to have an API to turn Tabby on/off?

**Comment by laxect** [comment]
You can just turn Tabline on or off. See <https://neovim.io/doc/user/options.html#'showtabline'>

**Comment by nanozuki** [comment]
For now, there is no toggle. But you can call `setup` again to set the `show_at_least` option. And call `:redrawtabline`.

I think this is a useful feature. I'll add it in the next version(Probably it will release next month).

**Comment by nanozuki** [comment]
@Pocco81 
With tabby.nvim 2.0 released, the `opt.showtabline` will be respected. You can use that option as wish.
