### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by stevenocchipinti** [nanozuki/tabby.nvim#83]
Hello,

Thanks for the Tabby plugin 🙏 

I created [a custom tabline in my config](https://github.com/stevenocchipinti/nvim/blob/02d6308be2cc54bb685fd6a4b88785c749769757/plugin/tabby.lua) but it no longer works with v2.
I do plan on upgrading to v2 eventually but I saw the readme mentions:
> Tabby thinks it's essential to stay backward compatible! So even if Tabby releases a brand new 2.0, it will not break the 1.0 configuration.

I thought I might be missing something simple so until I have the time to learn the new API and upgrade my code, is there an easy way to make my config work with the new version?
Or should I just lock the plugin to v1 until I update my tabline code?

Thanks?

**Comment by nanozuki** [comment]
> Is there an easy way to make my config work with the new version?

The config for v1.x works in v2.x, so you don't need to do anything after you upgrade `tabby.nvim`.

**Comment by stevenocchipinti** [comment]
I get the following error from [my config](https://github.com/stevenocchipinti/nvim/blob/02d6308be2cc54bb685fd6a4b88785c749769757/plugin/tabby.lua):
> tabby.lua:62: attempt to call field 'get_current_win' (a nil value)

This was coming from:
```
local tab = require("tabby.tab")
...
local focus_win = tab.get_current_win(tabid)
```

I still need to investigate further but it seems like these modules API have changed:
```
local tab = require("tabby.tab")
local win = require("tabby.win")
```

**Comment by nanozuki** [comment]
Oh, that function is not present in the README, I think no one uses it. I Only remain the function "public" in README.
Let me think about this problem...

**Comment by nanozuki** [comment]
After I read the diffrence of code,  I think this is important for V1.x users. I'll fix it in one or two days.

**Comment by stevenocchipinti** [comment]
Wow, thank you! 🙏 
That's quite a commitment to maintain backwards compatibility, much appreciated 🙂 

I'll eventually try out the new API, but everything is working for now 👍
