### ISSUE TITLE
Weird redraw issue when entering command mode

### ISSUE THREAD

**Issue by ReubenM** [nanozuki/tabby.nvim#92]
When entering command mode, the characters used for line.sep are all drawn with broken highlights until some sort of event later on causes it to get redrawn. Cannot figure out what could be causing this.
![vim_normal](https://user-images.githubusercontent.com/45847/200471234-b7f989f2-abba-4a2a-a8da-10cfd2597016.png)
![vim_command](https://user-images.githubusercontent.com/45847/200471307-3addea1e-dac8-469c-8a3e-f51d0d9d3027.png)

**Comment by ReubenM** [comment]
I should also add, I don't think this has anything to do with a broken config. It happens with all the presets also.

**Comment by nanozuki** [comment]
Oh, yes... I reproduced this bug. I will try to fix it.

**Comment by nanozuki** [comment]
![图片](https://user-images.githubusercontent.com/4208028/203348536-5e4df613-dc76-442e-b7c9-6d05758205fe.png)

I found that nvim will change the values of highlight groups in command mode...

Ok, I know how to fix it..
