### ISSUE TITLE
Why it's `win.buf().id` not `win.buf.id`?

### ISSUE THREAD

**Issue by nyngwang** [nanozuki/tabby.nvim#96]
As title. First, I appreciate this beautiful plugin and have a good time doing the customization. But regarding the coding part, It took me some time debugging to realize that `tabbywin.buf` is actually a function instead of a field. That is, the working code looks kinda cumbersome:

```lua
line.wins_in_tab(line.api.get_current_tab()).foreach(function(win)
  if not vim.api.nvim_buf_get_option(win.buf().id, 'buflisted') then return {} end
--                                        ^here
```

(In this code I assumed `win` should mean `tabby-win` as per your documentation)

---

At first, this is more of an aesthetic problem with the code. But then I notice that your documentation also said [`tabby.buf.id`](https://github.com/nanozuki/tabby.nvim#buf). Could you elaborate more on this part?

**Comment by nanozuki** [comment]
`win.buf()` is smillar to `tab.current_win()`, `line.tabs()`. These functions means "new tabby-buf object", "new tabby-win object," and "new tabby-tab object array".  I want to lazily calculate and build tabline.
The `tabby.buf.id` in the document should be a mistake.

**Comment by nyngwang** [comment]
Got it, then you can safely close this issue!
